return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "2021.03.23",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 512,
  height = 80,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 22,
  nextobjectid = 446,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "castle/obj0014.png",
      id = 11,
      name = "Image Layer 1",
      visible = true,
      opacity = 1,
      offsetx = -1,
      offsety = 221,
      parallaxx = 1,
      parallaxy = 1,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "castle/obj0015.png",
      id = 19,
      name = "Image Layer 2",
      visible = true,
      opacity = 1,
      offsetx = 2343,
      offsety = 221,
      parallaxx = 1,
      parallaxy = 1,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "castle/obj0017.png",
      id = 21,
      name = "Image Layer 3",
      visible = true,
      opacity = 1,
      offsetx = 4595,
      offsety = 212,
      parallaxx = 1,
      parallaxy = 1,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "castle/obj0016.png",
      id = 20,
      name = "Image Layer 4",
      visible = true,
      opacity = 1,
      offsetx = 6007,
      offsety = 201,
      parallaxx = 1,
      parallaxy = 1,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "bg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 136,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 113,
          height = 1280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "ceilingA",
          type = "",
          shape = "rectangle",
          x = 0,
          y = -96,
          width = 6248,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 113,
          y = 354,
          width = 33,
          height = 75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 113,
          y = 429,
          width = 108,
          height = 102,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 113,
          y = 531,
          width = 108,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 233,
          y = 489,
          width = 50,
          height = 152,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 283,
          y = 615,
          width = 58,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 242,
          y = 663,
          width = 66,
          height = 209,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 308,
          y = 710,
          width = 35,
          height = 51,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 308,
          y = 811,
          width = 66,
          height = 102,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 374,
          y = 819,
          width = 18,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 392,
          y = 870,
          width = 69,
          height = 101,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 461,
          y = 873,
          width = 20,
          height = 99,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 481,
          y = 937,
          width = 85,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 566,
          y = 1002,
          width = 93,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 288,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 659,
          y = 865,
          width = 149,
          height = 159,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 386,
          width = 125,
          height = 378,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 290,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 813,
          y = 523,
          width = 442,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1255,
          y = 409,
          width = 37,
          height = 135,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 292,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1292,
          y = 251,
          width = 110,
          height = 189,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1255,
          y = 409,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 37, y = -17 },
            { x = 37, y = 0 }
          },
          properties = {}
        },
        {
          id = 294,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1401,
          y = 224,
          width = 1,
          height = 27,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 295,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1292,
          y = 251,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 109, y = -27 },
            { x = 109, y = 0 }
          },
          properties = {}
        },
        {
          id = 296,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 837,
          y = 492,
          width = 62,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 461,
          width = 53,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 298,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 916,
          y = 492,
          width = 59,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "groundC",
          type = "",
          shape = "rectangle",
          x = 1041.5,
          y = 504.5,
          width = 52.3259,
          height = 31.8198,
          rotation = -46,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1095,
          y = 492,
          width = 57,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1123,
          y = 462,
          width = 54,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 302,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1162,
          y = 492,
          width = 62,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1198,
          y = 461,
          width = 57,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 233,
          y = 489,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 49, y = -10 },
            { x = 49, y = 0 }
          },
          properties = {}
        },
        {
          id = 305,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 282,
          y = 479,
          width = 1,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 364,
          width = 1,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 689,
          y = 364,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 104, y = 22 },
            { x = 0, y = 22 }
          },
          properties = {}
        },
        {
          id = 308,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1457,
          y = 414,
          width = 206,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 309,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1375,
          y = 436,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 47, y = -21 },
            { x = 47, y = 0 }
          },
          properties = {}
        },
        {
          id = 312,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1663,
          y = 414,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 1 },
            { x = 36, y = 14 },
            { x = 0, y = 14 }
          },
          properties = {}
        },
        {
          id = 313,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1698,
          y = 349,
          width = 111,
          height = 117,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 314,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1422,
          y = 415,
          width = 35,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 315,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1698,
          y = 349,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 110, y = -24 },
            { x = 110, y = 0 }
          },
          properties = {}
        },
        {
          id = 316,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 325,
          width = 1,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1816,
          y = 824,
          width = 23,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 321,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1839,
          y = 820,
          width = 38,
          height = 25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1877,
          y = 824,
          width = 168,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2045,
          y = 768,
          width = 63,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2108,
          y = 824,
          width = 527,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 325,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2339,
          y = 613,
          width = 65,
          height = 135,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2635,
          y = 768,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2698,
          y = 824,
          width = 168,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2866,
          y = 820,
          width = 38,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2904,
          y = 824,
          width = 23,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2927,
          y = 768,
          width = 17,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2934,
          y = 349,
          width = 111,
          height = 419,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 340,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 221,
          y = 544,
          width = 12,
          height = 94,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1454,
          y = 913,
          width = 40,
          height = 37,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 352,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1421,
          y = 874,
          width = 46,
          height = 39,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1384,
          y = 671,
          width = 37,
          height = 203,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 354,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1494,
          y = 944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 185, y = -36 },
            { x = 185, y = 0 }
          },
          properties = {}
        },
        {
          id = 355,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1679,
          y = 877,
          width = 135,
          height = 53,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1681,
          y = 466,
          width = 128,
          height = 302,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 357,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 1679,
          y = 877,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 137, y = -53 },
            { x = 137, y = 0 }
          },
          properties = {}
        },
        {
          id = 405,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 2916,
          y = 336,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 129, y = 13 },
            { x = 19, y = -11 },
            { x = 19, y = 13 }
          },
          properties = {}
        },
        {
          id = 406,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2934,
          y = 325,
          width = 1,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 3341,
          y = 224,
          width = 110,
          height = 337,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 3058,
          y = 414,
          width = 228,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 3045,
          y = 419,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 13, y = -5 },
            { x = 13, y = 13 },
            { x = 0, y = 13 }
          },
          properties = {}
        },
        {
          id = 410,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = 3286,
          y = 415,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 36, y = 0 },
            { x = 55, y = 8 },
            { x = 55, y = 17 },
            { x = 0, y = 17 }
          },
          properties = {}
        },
        {
          id = 415,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 3451,
          y = 523,
          width = 479,
          height = 38,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 3931,
          y = 409,
          width = 123,
          height = 186,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 808,
          y = 870,
          width = 81,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 889,
          y = 933,
          width = 43,
          height = 75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 707,
          y = 820,
          width = 101,
          height = 45,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 932,
          y = 998,
          width = 70,
          height = 90,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1002,
          y = 1054,
          width = 44,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1046,
          y = 1084,
          width = 42,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 1044,
          width = 45,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1142,
          y = 1025,
          width = 36,
          height = 22.6483,
          rotation = 23,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "sensors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 106,
          name = "block",
          type = "",
          shape = "rectangle",
          x = 2039,
          y = 791,
          width = 6,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "block",
          type = "",
          shape = "rectangle",
          x = 1402,
          y = 378,
          width = 11,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 366,
          width = 8,
          height = 474,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "block",
          type = "",
          shape = "rectangle",
          x = 1689,
          y = 392,
          width = 9,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "block",
          type = "",
          shape = "rectangle",
          x = 1816,
          y = 794,
          width = 5,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "exit",
          type = "",
          shape = "rectangle",
          x = 4023,
          y = 285,
          width = 31,
          height = 124,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "zoom_out",
          type = "",
          shape = "rectangle",
          x = 3451,
          y = 272,
          width = 197,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "others",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 436,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 160,
          y = 360,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 18,
      name = "collectibles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 359,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 312,
          y = 604,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 360,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 256,
          y = 472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 361,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 328,
          y = 696,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 362,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 328,
          y = 800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 363,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 471,
          y = 863,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 364,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 552,
          y = 928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 365,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 611,
          y = 991,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 366,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 672,
          y = 854,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 367,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 752,
          y = 363,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 368,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 856,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 369,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1229,
          y = 448,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 370,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1344,
          y = 224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 371,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1464,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 372,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1656,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 373,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1744,
          y = 328,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 374,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1840,
          y = 413,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 375,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1840,
          y = 557,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 376,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1840,
          y = 700,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 377,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1440,
          y = 862,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 378,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1481,
          y = 903,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 379,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 1584,
          y = 915,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 380,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2064,
          y = 758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 381,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2090,
          y = 758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 382,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2347,
          y = 603,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 383,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2363,
          y = 601,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 384,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2380,
          y = 601,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 385,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2396,
          y = 603,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 386,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2372,
          y = 576,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 387,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 2668,
          y = 757,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = 8 },
            { x = -8, y = 0 },
            { x = 0, y = -8 },
            { x = 8, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "ladders",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 231,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 664,
          y = 366,
          width = 24,
          height = 497,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "ptpfs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 233,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 664,
          y = 364,
          width = 24,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 400,
          width = 76,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 624,
          width = 76,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 736,
          width = 76,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2404,
          y = 744,
          width = 44,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 652,
          width = 56,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 347,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 588,
          width = 60,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 348,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 524,
          width = 56,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1264,
          y = 320,
          width = 28,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 350,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1400,
          y = 312,
          width = 40,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2404,
          y = 684,
          width = 44,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2404,
          y = 616,
          width = 44,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 460,
          width = 56,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3314,
          y = 380,
          width = 27,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3313,
          y = 332,
          width = 27,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3314,
          y = 284,
          width = 27,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3314,
          y = 236,
          width = 27,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 476,
          width = 27,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 428,
          width = 27,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1808,
          y = 512,
          width = 76,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 716,
          width = 56,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 396,
          width = 56,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "mvpfs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 70,
          name = "mvpf_v16",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 370,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "mvpf_h8",
          type = "",
          shape = "rectangle",
          x = 467,
          y = 369,
          width = 73,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "nmes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 146,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 1588,
          y = 364,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 1920,
          y = 764,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 337,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 2351,
          y = 757,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 2828,
          y = 761,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 784,
          y = 282,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 552,
          y = 428,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 548,
          y = 588,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 728,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 1198,
          y = 388,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 949,
          y = 392,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 1086,
          y = 414,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 744,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 588,
          y = 844,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "walkerBossA",
          type = "",
          shape = "ellipse",
          x = 3901,
          y = 248,
          width = 146,
          height = 155,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 1960,
          y = 552,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 1956,
          y = 456,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 840,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 2072,
          y = 696,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 2488,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 2484,
          y = 608,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 2664,
          y = 704,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 2736,
          y = 408,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 2784,
          y = 524,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "fg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "test",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 87,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 284,
          y = 575,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 1402,
          y = 355,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 714,
          y = 779,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 296,
          y = 555,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 1828,
          y = 776,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 296,
          y = 495,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 1402,
          y = 294,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 2116,
          y = 324,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
