return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "2021.03.23",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 276,
  height = 44,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 19,
  nextobjectid = 442,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "cyberpunked/obj0006_result.png",
      id = 11,
      name = "Image Layer 1",
      visible = false,
      opacity = 0.5,
      offsetx = 16,
      offsety = 10,
      parallaxx = 1,
      parallaxy = 1,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "cyberpunked/obj0007_result.png",
      id = 12,
      name = "Image Layer 2",
      visible = false,
      opacity = 0.5,
      offsetx = 2182,
      offsety = -11,
      parallaxx = 1,
      parallaxy = 1,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "grounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 124,
          name = "groundB",
          type = "",
          shape = "polygon",
          x = -276,
          y = 656,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 68, y = 16 },
            { x = 68, y = 32 },
            { x = 0, y = 16 }
          },
          properties = {}
        },
        {
          id = 276,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 688,
          width = 4384,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = -80,
          width = 16,
          height = 784,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 16,
          y = -80,
          width = 4384,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 4400,
          y = -80,
          width = 16,
          height = 784,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 656,
          width = 56,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 608,
          width = 236,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 544,
          width = 144,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 480,
          width = 236,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 524,
          y = 472,
          width = 236,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 486,
          y = 116,
          width = 86,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 116,
          width = 102,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 536,
          width = 236,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 294,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 816,
          y = 480,
          width = 88,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 295,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 128,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 64,
          width = 16,
          height = 300,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 298,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 208,
          width = 112,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 128,
          width = 16,
          height = 164,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 280,
          width = 112,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 352,
          width = 112,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 408,
          width = 112,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 56,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 136,
          width = 112,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 308,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 124,
          width = 160,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 124,
          width = 16,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 132,
          width = 16,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 486,
          y = 235,
          width = 86,
          height = 12,
          rotation = -15,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 486,
          y = 360,
          width = 86,
          height = 12,
          rotation = -15,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 388,
          y = 272,
          width = 86,
          height = 12,
          rotation = 15,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 460,
          width = 88,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 452,
          width = 88,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1372,
          y = 452,
          width = 68,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 452,
          width = 88,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1684,
          y = 448,
          width = 500,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 339,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 200,
          width = 220.359,
          height = 16,
          rotation = 10,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 304,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1752,
          y = 364,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1834,
          y = 364,
          width = 244.223,
          height = 16,
          rotation = 6,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1320,
          y = 240,
          width = 184,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2224,
          y = 448,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 2306,
          y = 448,
          width = 244.223,
          height = 7.95237,
          rotation = 10,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "sensors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 232,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 639,
          y = 204,
          width = 8,
          height = 228,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 943,
          y = 243,
          width = 8,
          height = 253,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 1272,
          y = 244,
          width = 8,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "exit",
          type = "",
          shape = "rectangle",
          x = 4392,
          y = 564,
          width = 7,
          height = 124,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 2200,
          y = 452,
          width = 8,
          height = 196,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 18,
      name = "collectibles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 310,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 32,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 311,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 40,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 312,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 48,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 313,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 56,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 314,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 64,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 315,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 72,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 316,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 80,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 317,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 88,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 318,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 96,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 319,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 104,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 320,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 112,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 321,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 120,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 322,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 128,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 323,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 136,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 324,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 144,
          y = 112,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 325,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 152,
          y = 104,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 345,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 720,
          y = 196,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 346,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 752,
          y = 201,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 347,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 784,
          y = 206,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 348,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 816,
          y = 212,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 349,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 848,
          y = 218,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 350,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 880,
          y = 224,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 364,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 216,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 365,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 248,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 366,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 280,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 367,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 344,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 368,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 312,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 369,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 280,
          y = 272,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 370,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 216,
          y = 344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 371,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 248,
          y = 344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 372,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 280,
          y = 344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 373,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 528,
          y = 340,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 374,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 432,
          y = 276,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 375,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 528,
          y = 216,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 376,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 568,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 377,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 616,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 378,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 664,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 379,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 712,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 380,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 760,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 381,
          name = "c01",
          type = "",
          shape = "polygon",
          x = 808,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = 0 },
            { x = 0, y = -8 },
            { x = -8, y = 0 },
            { x = 0, y = 8 },
            { x = 8, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "ladders",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 231,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 631,
          y = 204,
          width = 24,
          height = 264,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 936,
          y = 243,
          width = 24,
          height = 289,
          rotation = 0,
          visible = false,
          properties = {}
        },
        {
          id = 359,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 1264,
          y = 244,
          width = 24,
          height = 205,
          rotation = 0,
          visible = false,
          properties = {}
        },
        {
          id = 403,
          name = "ladder",
          type = "",
          shape = "rectangle",
          x = 2192,
          y = 452,
          width = 24,
          height = 232,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "ptpfs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 286,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 200,
          width = 88,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 905,
          y = 239,
          width = 85,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 354,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 524,
          y = 611,
          width = 324,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 240,
          width = 88,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1397,
          y = 375,
          width = 55,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2184,
          y = 448,
          width = 40,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1684,
          y = 620,
          width = 508,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 1744,
          y = 552,
          width = 448,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2384,
          y = 620,
          width = 668,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2546,
          y = 491,
          width = 62,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 2546,
          y = 552,
          width = 62,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3628,
          y = 620,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3760,
          y = 560,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 3888,
          y = 504,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "ptpf",
          type = "",
          shape = "rectangle",
          x = 18,
          y = 606,
          width = 108,
          height = 5.7629,
          rotation = 19,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "mvpfs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 288,
          name = "mvpf_S84",
          type = "",
          shape = "rectangle",
          x = 573,
          y = 116,
          width = 27,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "mvpf_N172",
          type = "",
          shape = "rectangle",
          x = 1117,
          y = 632,
          width = 34,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "mvpf_E190",
          type = "",
          shape = "rectangle",
          x = 991,
          y = 239,
          width = 50,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 382,
          name = "mvpf_S180",
          type = "",
          shape = "rectangle",
          x = 1336,
          y = 452,
          width = 28,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "mvpf_S164",
          type = "",
          shape = "rectangle",
          x = 1655,
          y = 448,
          width = 28,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "playable",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 146,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 1192,
          y = 624,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 1604,
          y = 620,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 1972,
          y = 628,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 2512,
          y = 632,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 704,
          y = 624,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 472,
          y = 48,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 0,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 712,
          y = 264,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 712,
          y = 404,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 868,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 780,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 868,
          y = 428,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 152,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "flyerKeepA",
          type = "",
          shape = "rectangle",
          x = 856,
          y = 168,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "flyerA",
          type = "",
          shape = "rectangle",
          x = 1096,
          y = 188,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 1836,
          y = 292,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 2080,
          y = 560,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 2720,
          y = 560,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "walkerBossA",
          type = "",
          shape = "ellipse",
          x = 4044,
          y = 468,
          width = 131,
          height = 164,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "walkerA",
          type = "",
          shape = "ellipse",
          x = 3405,
          y = 609,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 20,
          y = 532,
          width = 51,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "fg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "test",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 87,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 312,
          y = 648,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 2368,
          y = 560,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 1708,
          y = 560,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 2552,
          y = 492,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 1112,
          y = 648,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 296,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 200,
          y = 88,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 552,
          y = 628,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 309,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 444,
          y = 300,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 1256,
          y = 412,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 956,
          y = 496,
          width = 43,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "player1j",
          type = "",
          shape = "ellipse",
          x = 3840,
          y = 500,
          width = 43,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
